### ISSUE TITLE
Support for Windows (termios issue)

### ISSUE THREAD

**Issue by victoriahendersonn** [crs4/rocrate-validator#12]
Hello,

First off, thank you for the great work on this project! I've recently been using the RO-Crate Validator for my research project, it has been incredibly helpful. 

However, I did want to ask a question about something I've ran into when trying to use the validator on my Windows machine (I usually use MacOS, so I only encountered this recently). Specifically, the validator throws a `ModuleNotFoundError` related to `termios`, which I understand is a Unix-specific module (from reading the [documentation](https://docs.python.org/3/library/termios.html)). Below is the traceback I encountered:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  ...
  File "C:\Users\Victoria\rocrate-validator\rocrate_validator\cli\commands\validate.py", line 19, in <module>
    import termios
ModuleNotFoundError: No module named 'termios'
```

Here are the steps I followed to setup the validator:
1. `git clone https://github.com/crs4/rocrate-validator.git`
2. `cd rocrate-validator`
3. `python3 -m venv .venv`
4. `. .venv/bin/activate`
5. `poetry install`
6. `poetry run rocrate-validator validate <path_to_rocrate>`  # inserting a path to a specified ROCrate

Would it be possible to add support for Windows in future releases? Although I understand this might required changing how terminal interactions are handled. Also, please let me know if I've just been setting this up wrong!

Regardless, thank you again for your time and all the effort you put into this project! :)

**Comment by ilveroluca** [comment]
Hi @victoriahendersonn.  Thanks for providing this feedback.  You may very well be the first Windows user to try this software :-)

We're going to look at the options we have to fix this problem.

**Comment by kikkomep** [comment]
Hi @victoriahendersonn. I've fixed the issue with the `termios` module and made some other small changes to support Windows. 
You can find the updates on the develop branch. 
Let us know how it goes!

**Comment by ilveroluca** [comment]
@victoriahendersonn can we close this issue?
