### ISSUE TITLE
Only a small subset of possible ISO 8601 datetimes for datePublished is accepted

### ISSUE THREAD

**Issue by salexan2001** [crs4/rocrate-validator#26]
Hello,

during testing the rocrate-validator on some examples for the ELN-File Format, I stumbled upon the following issue for the [root data entity metadata](https://github.com/crs4/rocrate-validator/blob/develop/rocrate_validator/profiles/ro-crate/must/2_root_data_entity_metadata.ttl):

The regexp for
```
        sh:path schema_org:datePublished ;
        sh:pattern "^(\\d{4}-\\d{2}-\\d{2})(T\\d{2}:\\d{2}:\\d{2}(\\.\\d{3})?\\+\\d{2}:\\d{2})?$" ;
```

seems to much to strict:

[ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) e.g. allows specifying times without time zone designators or times without giving the secons.

**Comment by kikkomep** [comment]
Hi @salexan2001, thank you for your feedback.
The PR #29 should fix this issue.
