### ISSUE TITLE
Validate ro-crate-metadata.json is flattened

### ISSUE THREAD

**Issue by dnlbauer** [crs4/rocrate-validator#27]
Hi,

The RO-Crate documentation mentions that the JSON-LD in a valid ro-crate-metadata.json file is flattened:

https://www.researchobject.org/ro-crate/specification/1.1/structure.html
> The RO-Crate Metadata File MUST contain RO-Crate JSON-LD; a valid [JSON-LD 1.0](https://www.w3.org/TR/2014/REC-json-ld-20140116/) document in [flattened](https://www.w3.org/TR/json-ld/#flattened-document-form) and [compacted](https://www.w3.org/TR/json-ld/#compacted-document-form) form

From my tests, the validator does not validate against it. I.e. here is an unflattend JSON-LD that is recognized as a valid RO-Crate:

```json
{
    "@context": "https://w3id.org/ro/crate/1.1/context",
    "@graph": [
        {
            "@type": "CreativeWork",
            "@id": "ro-crate-metadata.json",
            "conformsTo": {
                "@id": "https://w3id.org/ro/crate/1.1"
            },
            "about": {
                "@type": "Dataset",
                "@id": "./",
                "hasPart": [
                    {
                        "@type": "File",
                        "@id": "test.csv",
                        "encodingFormat": "text/csv",
                        "name": "This is a test file",
                        "description": "This is a test dataset"
                    }
                ],
                "name": "This is a test dataset",
                "description": "This is a test dataset",
                "license": {
                    "@id": "https://creativecommons.org/licenses/by/4.0/"
                },
                "datePublished": "2024-11-05"
            }
        }
    ]
}
```

**Comment by simleo** [comment]
I've found an example of unflattened RO-Crate that is still recognized as valid:

```json
{
    "@context": "https://w3id.org/ro/crate/1.1/context",
    "@graph": [
        {
            "@id": "ro-crate-metadata.json",
            "@type": "CreativeWork",
            "about": {"@id": "./"},
            "conformsTo": {"@id": "https://w3id.org/ro/crate/1.1"}
        },
        {
            "@id": "./",
            "@type": "Dataset",
            "name": "not_flattened",
            "description": "not_flattened",
            "license": "Apache-2.0",
            "datePublished": "2024-11-12",
            "hasPart": [{"@id": "somedir/"}]
        },
        {
            "@id": "somedir/",
            "@type": "Dataset",
            "name": "dataset",
            "description": "dataset",
            "variableMeasured": [
                {
                    "@type": "PropertyValue",
                    "propertyID": "https://example.org/terms/ru#realTime",
                    "name": "realTime",
                    "value": "42"
                }
            ]
        }
    ]
}
```

I ran

```
rocrate-validator -y validate -v -w 79 -nff -p ro-crate -o err.txt -l REQUIRED <crate>
```

**Comment by dnlbauer** [comment]
@simleo good catch!

So the reason for this is, that I (faulty) assumed that nested blocks always have an `@id` at this line:
https://github.com/crs4/rocrate-validator/blob/bcbe82904caff9c4b1c9fd3b042ed119fb33ba38/rocrate_validator/profiles/ro-crate/must/0_file_descriptor_format.py#L112

Basically, it says "if there is a nested dict, and the dict has an `@id`, it must not have any other properties".  Your nested entity does not have an id and is therefore falling through my net.

One option would be to assume that a dictionary that is not on `@graph` level always has to follow the format `{"@id": "..."}`. The check would then be:

```python
if "@id" not in entity or len(entity) > 1: 
    return False
```
