### ISSUE TITLE
validate command in CLI does not support ZIP files

### ISSUE THREAD

**Issue by jmanideep** [crs4/rocrate-validator#43]
The `rocrate-validator validate <path_to_rocrate>` CLI command (with default severity) is not working when provided with a path to a ZIP file containing RO-Crate. However, the same content was valid after unzipping the file, and the path to the extracted folder was used.

A [sample ZIP file](https://github.com/user-attachments/files/17827643/test-record.zip) used for testing has been attached to this issue for reference.

**Environment:**
* `roc-validator` version: 0.4.6
* Profile used for validation:  ro-crate-1.1

**Comment by simleo** [comment]
@jmanideep The sample ZIP archive you provided has a top-level `test-record` directory that contains `ro-crate-metadata.json`. A zipped RO-Crate has to contain `ro-crate-metadata.json` at the top level. See [the spec](https://www.researchobject.org/ro-crate/specification/1.1/structure.html#table-of-contents):

> if an *RO-Crate* is archived in a ZIP-file, the ZIP root directory is an *RO-Crate root* directory if it contains `ro-crate-metadata.json`.

An example of a service that consumes zipped RO-Crates is https://workflowhub.eu/, which requires ZIP files to have `ro-crate-metadata.json` at the top level.
