### ISSUE TITLE
Using a list as type does not lead to validation failure

### ISSUE THREAD

**Issue by salexan2001** [crs4/rocrate-validator#48]
I validated an rocrate-file with a `ro-crate-metadata.json` that started like this:
```json
{
  "@context": "https://w3id.org/ro/crate/1.1/context",
  "@graph": [
    {
      "@id": "./",
      "name": "test-name",
      "description": "test-description",
      "license": "test-license",
      "datePublished": "2024-12-01T11:29",
      "@type": ["Dataset"],
      "hasPart": {
        "@id": "records-example/"
      }
    },
```

In the [specification](https://www.researchobject.org/ro-crate/specification/1.1/root-data-entity.html#direct-properties-of-the-root-data-entity) we can see that "@type: MUST be [Dataset](http://schema.org/Dataset)".

Although the type is ["Dataset"], here, the file is successfully validated by rocrate-validator.

**Comment by kikkomep** [comment]
According to the [specifications](https://www.researchobject.org/ro-crate/specification/1.1/data-entities#referencing-files-and-folders-from-the-root-data-entity), a `RooDataEntity` is a type of Data Entity and

> “Data Entities can also represent other types, such as an online database.”

In the same section of the [specifications](https://www.researchobject.org/ro-crate/specification/1.1/data-entities#referencing-files-and-folders-from-the-root-data-entity), you can also find an example  that is similar to yours.
